config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # devise_scope :user do
    # Redirests signing out users back to sign-in
    # get 'users', to: 'devise/sessions#new'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :suppliers
  resources :users, only: %i[index show edit update destroy]
  resources :qualities
  resources :services

  namespace :api do
    resources :qualities, only: %i[suppliers] do
      get :suppliers
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  include ServicesHelper

  validates :datetime_of_service, :status, :service_number, presence: true
  validates :service_number, uniqueness: true
  before_validation :set_params_to_create_service
  after_create :create_service_history
  after_update :create_service_history

  belongs_to :quality
  belongs_to :user
  belongs_to :supplier
  has_many :service_histories

  enum status: {
    created: 0,
    reviewing: 1,
    checking: 2,
    executing: 3,
    paying: 4,
    finished: 5,
    guarantee: 6
  }

  private

  def set_params_to_create_service
    return unless new_record?

    self.status = Service.statuses[:created]
    self.service_number = generate_service_number
  end

  def create_service_history
    service_history = ServiceHistory.new
    service_history.create_service_history_by_service(self)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to :services
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to services_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path
  end

  private

  def service_params
    params.require(:service)
          .permit(
            :quality_id,
            :supplier_id,
            :datetime_of_service,
            :comment
          )
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def format_service_number(service_number)
    format('%05d', service_number)
  end

  def generate_service_number
    Service.all.empty? ? 1 : Service.all.last.service_number.to_i + 1
  end

  def get_status_from_i18n(status)
    case status
    when 'created'
      I18n.t('services.statuses.created')
    when 'reviewing'
      I18n.t('services.statuses.created')
    when 'checking'
      I18n.t('services.statuses.created')
    when 'executing'
      I18n.t('services.statuses.created')
    when 'paying'
      I18n.t('services.statuses.created')
    when 'finished'
      I18n.t('services.statuses.created')
    when 'guarantee'
      I18n.t('services.statuses.created')
    else
      ''
    end
  end
end

app/views/services/_form.html.slim
= simple_nested_form_for @service do |form|
  .form-inputs
    div data-controller='services'
      .row.align-items-start
        .col
          .form-outline.mb-4
            = form.association :quality,
              label: I18n.t('services.form.quality'),
              include_blank: false,
              input_html: { \
                'data-action': 'change->services#show_suppliers_by_quality', \
                'data-services-target': 'quality' \
              }
        .col
          .form-outline.mb-4
            = form.association :supplier,
              label: I18n.t('services.form.supplier'),
              include_blank: false,
              input_html: { 'data-services-target': 'suppliers' }
      .row.align-items-start
        .col
          .form-outline.mb-4
            = form.label I18n.t('services.form.datetime_of_service')
            = form.datetime_local_field :datetime_of_service, class: 'form-control'
        .col
          .form-outline.mb-4
            = form.label I18n.t('services.form.comment')
            = form.text_area :comment, class: 'form-control'
      - if !@service.new_record?
        .row.align-items-start
          .col
            .form-outline.mb-4
              = form.input :status,
                collection: Service.statuses.keys.map {|status| get_status_from_i18n(status)},
                label: I18n.t('services.form.status'),
                disabled: true,
                include_blank: false,
                selected: @service.status
          .col
            .form-outline.mb-4
              = form.input :service_number,
                label: I18n.t('services.form.service_number'),
                disabled: true
    = form.button :submit,
      @service.new_record? ? I18n.t('services.new.button') : I18n.t('services.edit.button'),
      class: 'btn btn-primary mt-2'

app/views/services/edit.html.slim
h1 = I18n.t('services.edit.title')

= render 'form'

app/views/services/index.html.slim
h1 = I18n.t('services.title')
= link_to(I18n.t('services.index_table.new_service'), new_service_path, class: 'btn btn-primary float-right')
table.table.table-striped
  thead
    tr
      th = I18n.t('services.index_table.service_number')
      th = I18n.t('services.index_table.user')
      th = I18n.t('services.index_table.supplier')
      th = I18n.t('services.index_table.quality')
      th = I18n.t('services.index_table.datetime_of_service')
      th = I18n.t('services.index_table.status')
      th = I18n.t('services.index_table.actions')
  tbody
    - @services.each do |service|
      tr
        td = format_service_number(service.service_number)
        td = service.user.name
        td = service.supplier.name
        td = service.quality.name
        td = service.datetime_of_service.strftime("%Y-%m-%d %I:%M %p")
        td = get_status_from_i18n service.status
        td
          = link_to(I18n.t('shared.buttons.show'), service_path(service), class: 'btn btn-primary')
          = link_to(I18n.t('shared.buttons.edit'), edit_service_path(service), class: 'btn btn-primary ms-1')
          = link_to(I18n.t('shared.buttons.delete'), service_path(service), class: 'btn btn-danger ms-1', data: { turbo_method: :delete, turbo_confirm: I18n.t('services.delete.confirmation') })

app/views/services/new.html.slim
h1 = I18n.t('services.new.title')

= render 'form'

app/views/services/show.html.slim
h1 = I18n.t('services.show.title')
br
.container
  .row
    .col
      strong = I18n.t('services.form.user')
      = ": #{@service.user.name} #{@service.user.lastname}"
  .row
    .col
      strong = I18n.t('services.form.quality')
      = ": #{@service.quality.name}"
  .row
    .col
      strong = I18n.t('services.form.supplier')
      = ": #{@service.supplier.name}"
  .row
    .col
      strong = I18n.t('services.form.datetime_of_service')
      = ": #{@service.datetime_of_service.strftime("%Y-%m-%d %I:%M %p")}"
  .row
    .col
      strong = I18n.t('services.form.status')
      = ": #{get_status_from_i18n @service.status }"
  .row
    .col
      strong = I18n.t('services.form.comment')
      = ": #{@service.comment}"