config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # devise_scope :user do
    # Redirests signing out users back to sign-in
    # get 'users', to: 'devise/sessions#new'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :suppliers
  resources :users, only: %i[index show edit update destroy]
  resources :qualities
  resources :services

  namespace :api do
    resources :qualities, only: %i[suppliers] do
      get :suppliers
    end
  end
end

app/views/shared/_messages.html.slim
- if notice
  p.alert.alert-success
    = notice
- if alert
  p.alert.alert-warning
    = alert

app/views/shared/_nav.html.slim
.container-fluid
  .row
    .col-md-12
      ul.nav.navbar style=("background-color: #e3f2fd;")
        li.nav-item
          = link_to(I18n.t('shared.navbar.home'), root_path, class: 'nav-link')
        li.nav-item
          = link_to(I18n.t('shared.navbar.users'), users_path, class: 'nav-link')
        li.nav-item
          = link_to(I18n.t('shared.navbar.suppliers'), suppliers_path, class: 'nav-link')
        li.nav-item
          = link_to(I18n.t('shared.navbar.services'), services_path, class: 'nav-link')
        li.nav-item
          = link_to(I18n.t('shared.navbar.qualities'), qualities_path, class: 'nav-link')
        - if user_signed_in?
          li.nav-item.ms-auto
            = link_to(I18n.t('shared.navbar.edit_registration'), edit_user_registration_path, class: 'nav-link')
          li.nav-item
            = link_to(I18n.t('shared.navbar.log_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link')
        - else
          li.nav-item
            = link_to(I18n.t('shared.navbar.register'), new_user_registration_path, class: 'nav-link')
          li.nav-item
            = link_to(I18n.t('shared.navbar.log_in'), new_user_session_path, class: 'nav-link')