config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # devise_scope :user do
    # Redirests signing out users back to sign-in
    # get 'users', to: 'devise/sessions#new'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :suppliers
  resources :users, only: %i[index show edit update destroy]
  resources :qualities
  resources :services

  namespace :api do
    resources :qualities, only: %i[suppliers] do
      get :suppliers
    end
  end
end

app/models/quality.rb
class Quality < ApplicationRecord
  validates :name, presence: true

  has_and_belongs_to_many :suppliers
  has_many :services
end

app/controllers/api/qualities_controller.rb
module Api
  class QualitiesController < BaseController
    def suppliers
      suppliers = Quality.find(params[:quality_id]).suppliers
      respond_with suppliers, json: suppliers
    end
  end
end

app/controllers/qualities_controller.rb
class QualitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :assign_quality, only: %i[show edit update destroy]

  def index
    @qualities = Quality.all
  end

  def new
    @quality = Quality.new
  end

  def create
    @quality = Quality.new(quality_params)

    if @quality.save
      redirect_to quality_path(@quality)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @quality.update(quality_params)
      redirect_to quality_path(@quality)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quality.destroy
    redirect_to qualities_path
  end

  private

  def quality_params
    params.require(:quality)
          .permit(
            :name,
            :description
          )
  end

  def assign_quality
    @quality = Quality.find(params[:id])
  end
end

app/helpers/qualities_helper.rb
module QualitiesHelper
end

app/views/qualities/_form.html.slim
= simple_form_for @quality do |form|
  .form_inputs
    .row.align-items-start
      .col
        .form-outline.mb-4
          = form.input :name, label: I18n.t('qualities.form.name')
      .col
        .form-outline.mb-4
          = form.input :description, label: I18n.t('qualities.form.description')
  = form.button :submit,
    @quality.new_record? ? I18n.t('qualities.new.button') : I18n.t('qualities.edit.button'),
    class: 'btn btn-primary mt-2'

app/views/qualities/edit.html.slim
h1 = I18n.t('qualities.edit.title')

= render 'form'

app/views/qualities/index.html.slim
h1 = I18n.t('qualities.title')
= link_to(I18n.t('qualities.index_table.new_quality'), new_quality_path, class: 'btn btn-primary float-right')
table.table.table-striped
  thead
    tr
      th = I18n.t('qualities.index_table.name')
      th = I18n.t('qualities.index_table.description')
      th = I18n.t('qualities.index_table.actions')
  tbody
    - @qualities.each do |quality|
      tr
        td = quality.name
        td = quality.description
        td
          = link_to(I18n.t('shared.buttons.show'), quality_path(quality), class: 'btn btn-primary')
          = link_to(I18n.t('shared.buttons.edit'), edit_quality_path(quality), class: 'btn btn-primary ms-1')
          = link_to(I18n.t('shared.buttons.delete'), quality_path(quality), class: 'btn btn-danger ms-1', data: { turbo_method: :delete, turbo_confirm: I18n.t('qualities.delete.confirmation') })

app/views/qualities/new.html.slim
h1 = I18n.t('qualities.new.title')

= render 'form'

app/views/qualities/show.html.slim
h1 = I18n.t('qualities.show.title')
br
.container
  .row
    .col
      strong = I18n.t('qualities.form.name')
      = ": #{@quality.name}"
  .row
    .col
      strong = I18n.t('qualities.form.description')
      = ": #{@quality.description}"