config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # devise_scope :user do
    # Redirests signing out users back to sign-in
    # get 'users', to: 'devise/sessions#new'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :suppliers
  resources :users, only: %i[index show edit update destroy]
  resources :qualities
  resources :services

  namespace :api do
    resources :qualities, only: %i[suppliers] do
      get :suppliers
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true

  belongs_to :address
  has_and_belongs_to_many :qualities
  has_many :services

  accepts_nested_attributes_for :address
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :assign_supplier, only: %i[show edit update destroy]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
    @supplier.build_address
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to :suppliers
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @supplier.destroy
    redirect_to suppliers_path
  end

  private

  def supplier_params
    params.require(:supplier)
          .permit(
            :name,
            :photo,
            quality_ids: [],
            address_attributes: %i[id street city state country]
          )
  end

  def assign_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.slim
= simple_nested_form_for @supplier do |form|
  .form-inputs
    h3 = I18n.t('suppliers.form.main_information')
    .row.align-items-start
      .col
        .form-outline.mb-4
          = form.input :name, label: I18n.t('suppliers.form.name')
      .col
        .form-outline.mb-4
          = form.input :photo, label: I18n.t('suppliers.form.photo')
    .row.align-items-start
      .col
        .form-outline.mb-4
          = form.association :qualities, as: :check_boxes,
            wrapper: :horizontal_collection_inline,
            label: I18n.t('suppliers.form.quialities')

  h3 = I18n.t('suppliers.form.address')
  = form.fields_for :address do |address_form|
    .row.align-items-start
        .col
          .form-outline.mb-4
            = address_form.input :street, label: I18n.t('suppliers.form.street')
          .form-outline.mb-4
            = address_form.input :state, label: I18n.t('suppliers.form.state')
        .col
          .form-outline.mb-4
            = address_form.input :city, label: I18n.t('suppliers.form.city')
          .form-outline.mb-4
            = address_form.input :country, :as => :string, label: I18n.t('suppliers.form.country')
  = form.button :submit,
    @supplier.new_record? ? I18n.t('suppliers.new.button') : I18n.t('suppliers.edit.button'),
    class: 'btn btn-primary mt-2'

app/views/suppliers/edit.html.slim
h1 = I18n.t('suppliers.edit.title')

= render 'form'

app/views/suppliers/index.html.slim
h1 = I18n.t('suppliers.title')
= link_to(I18n.t('suppliers.index_table.new_supplier'), new_supplier_path, class: 'btn btn-primary float-right')

table.table.table-striped
  thead
    tr
      th = I18n.t('suppliers.index_table.name')
      th = I18n.t('suppliers.index_table.city')
      th = I18n.t('suppliers.index_table.state')
      th = I18n.t('suppliers.index_table.country')
      th = I18n.t('suppliers.index_table.actions')
  tbody
    - @suppliers.each do |supplier|
      tr
        td = supplier.name
        td = supplier.address.city
        td = supplier.address.state
        td = supplier.address.country
        td
          = link_to(I18n.t('shared.buttons.show'), supplier_path(supplier), class: 'btn btn-primary')
          = link_to(I18n.t('shared.buttons.edit'), edit_supplier_path(supplier), class: 'btn btn-primary ms-1')
          = link_to(I18n.t('shared.buttons.delete'), supplier_path(supplier), class: 'btn btn-danger ms-1', data: { turbo_method: :delete, turbo_confirm: I18n.t('suppliers.delete.confirmation') })

app/views/suppliers/new.html.slim
h1 = I18n.t('suppliers.new.title')

= render 'form'

app/views/suppliers/show.html.slim
h1 = I18n.t('suppliers.show.title')
br
.container
  h4 = I18n.t('suppliers.form.main_information')
  .row
    .col
      strong = I18n.t('suppliers.form.name')
      = ": #{@supplier.name}"
  br
  h4 = I18n.t('suppliers.form.address')
  .row
    .col
      strong = I18n.t('suppliers.form.street')
      = ": #{@supplier.address.street}"
  .row
    .col
      strong = I18n.t('suppliers.form.city')
      = ": #{@supplier.address.city}"
  .row
    .col
      strong = I18n.t('suppliers.form.state')
      = ": #{@supplier.address.state}"
  .row
    .col
      strong = I18n.t('suppliers.form.country')
      = ": #{@supplier.address.country}"